Add passphrase to client key signing

diff --git a/templates/revoke.sh.j2 b/templates/revoke.sh.j2
--- a/templates/revoke.sh.j2
+++ b/templates/revoke.sh.j2
@@ -7,13 +7,24 @@ cd ${CADIR}
 
 gen_crl () {
   # regenerate the certificate revocation list
-  openssl ca -gencrl -config ca.conf -out ca-crl.pem
+  if [ "${passphrase}" ]
+  then
+    openssl ca -gencrl -config ca.conf -out ca-crl.pem -passin "pass:${passphrase}"
+  else
+    openssl ca -gencrl -config ca.conf -out ca-crl.pem
+  fi
+
 }
 
 revoke () {
   # revoke a client certificate
-  openssl ca -config ca.conf -revoke "${1}"
-}
+  if [ "${passphrase}" ]
+  then
+    openssl ca -config ca.conf -revoke "${cert}" -passin "pass:${passphrase}"
+  else
+    openssl ca -config ca.conf -revoke "${cert}"
+  fi
+} 
 
 crl_out () {
   # show certificate revocation list
@@ -31,13 +42,23 @@ crl_verify () {
   rm -f ${temp_pem}
 }
 
+while getopts ":c:p:" opt; do
+  case $opt in
+    c) cert="$OPTARG"
+    ;;
+    p) passphrase="$OPTARG"
+    ;;
+    \?) echo "Invalid option -$OPTARG" >&2
+    ;;
+  esac
+done
+
 gen_crl
 
-if [ "${1}" ]
+if [ "${cert}" ]
 then
-  revoke "${1}"
+  revoke "${cert}"
   gen_crl
 fi
-
 
 # vim: autoindent expandtab shiftwidth=2
